name: 'Delete old artifacts'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@04c636a505f26ebc82f8d070b202fb87ff572b10 # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1hr